### PR TITLE
ENG-1231: Add CORS to polylang-server

### PR DESCRIPTION
**Pull request by timmyjose**
Changes:
  - set CORS for `polylang server` (prover) to "permissive" (this may be changed later, if needed).
  - added `overflow-addrs` field to `Output` in the prover (used by the verifier).`

This is to update the `polylang-server` deployment so that we can use it in the playground instead of a local instance.

Dependent: #134

### CODE REVIEW

**Comment by timmyjose** [comment]
(Side note: We should probably increase the time out for the tests, perhaps? It seems to time out quite frequently around this time of day).

**Comment by timmyjose** [comment]
Removed `verify` endpoint. As discussed on Linear, the idea is to use a common (independent) `verify` function in the WASM API itself.

**Review by calummoore — APPROVED** [review]
This is fine, I guess it depends on the previous PR?

**Comment by timmyjose** [comment]
> This is fine, I guess it depends on the previous PR?

The other PR (#134) depends on this one (to set CORs on the prover). So this can be merged in, and then that PR (after changes) can use the prover url (right now it's `localhost`) for final testing.

**Pull request merged**
