### PR TITLE
Implement prover server

### PR DESCRIPTION
**Pull request by mateuszmlc**
Contains #123 

Example calling main:
`cargo run --bin compile -- function:main <<<'function main(a: u32, b: u32): u32 { return a + b; }' >/tmp/code && http POST :8090/prove midenCode="$(cat /tmp/code)" abi:='{"std_version":"0.6.1","this_addr":null,"this_type":null,"result_addr":29,"result_type":{"PrimitiveType":"UInt32"},"param_types":[{"PrimitiveType":"UInt32"},{"PrimitiveType":"UInt32"}],"other_records":[],"other_contract_types":[],"dependent_fields":[]}'  args:='[1, 3]'`

Example calling Account#test:
`cargo run --bin compile -- contract:Account function:test <<<'@public contract Account { id: string; test() { }  }' >/tmp/code && http POST :8090/prove midenCode="$(cat /tmp/code)" abi:='{"std_version":"0.6.1","this_addr":38,"this_type":{"Struct":{"name":"Account","fields":[["id","String"]]}},"result_addr":null,"result_type":null,"param_types":[],"other_records":[{"contract":"Account"}],"other_contract_types":[{"Struct":{"name":"Account","fields":[["id","String"]]}}],"dependent_fields":[]}' this:='{"id": "test"}' thisSalts:='[0]' args:='[]' otherRecords:='{}'`

### CODE REVIEW

**Comment by calummoore** [comment]
Can we make this into a callable API? I think we already have this in the polybase-rust repo, so should be just a lift and shift.

**Review by calummoore — CHANGES_REQUESTED** [review]
Can we make this into a callable API? I think we already have this in the polybase-rust repo, so should be just a lift and shift.

**Comment by mateuszmlc** [comment]
> Can we make this into a callable API? I think we already have this in the polybase-rust repo, so should be just a lift and shift.

Yeah, doing that right now, exporting the route to a "server-routes" package and importing it from polybase-rust

**Comment by mateuszmlc** [comment]
@calummoore It's tricky to reuse because we don't want to use the main branch on polybase-rust, as we made breaking changes since then. Do we need this now?

**Comment by calummoore** [comment]
I just meant to copy the code into this repo - i.e. just create a little server crate in polylang.

**Comment by mateuszmlc** [comment]
> I just meant to copy the code into this repo - i.e. just create a little server crate in polylang repo.

I did mostly copy the code for the prove route from the polybase-rust repo, with some changes since then, like including return values in the response, and made a server crate with an actix-web server

**Comment by mateuszmlc** [comment]
> Is this ready to review?

Yes. Was thinking of maybe reverting https://github.com/polybase/polylang/pull/124/commits/4777b4f71e9a65bb6df99fd2cc0a5bbd2114d47e if we're not re-using it, but it sounds like a good idea to separate the routes and server so we can reuse them later, say for CLI, so I think it's better to keep the crate and remove it later if it's inconvenient in the future

**Review by calummoore — APPROVED** [review]

**Pull request merged**
