### PR TITLE
ENG-1056: Add examples for `Polylang`

### PR DESCRIPTION
**Pull request by timmyjose**
Changes:
  - added `examples` directory in the root.
  - added a couple of examples.

### CODE REVIEW

**Review by mateuszmlc — APPROVED** [review]
Nice. Do we need a separate crate for each example, or could we just have examples/account-balances.rs etc.? i.e. use the rust native examples that get run with `cargo run --example <name>`

**Comment by timmyjose** [comment]
> Nice. Do we need a separate crate for each example, or could we just have examples/account-balances.rs etc.? i.e. use the rust native examples that get run with `cargo run --example <name>`

You're right! Initially, I thought of having full-fledged examples that could run in their separate packages, but seeing as to how most of the code is common code, it makes sense to bundle the examples in the main package. I'll update the PR and push the changes.

**Review by mateuszmlc — APPROVED** [review]

**Comment by calummoore** [comment]
Nice, can we add these to the playground too?

**Comment by timmyjose** [comment]
> Nice, can we add these to the playground too?

Cool. I'll add these to the playground as well. 👍 .

**Comment by timmyjose** [comment]
> > Nice, can we add these to the playground too?
> 
> Cool. I'll add these to the playground as well. 👍 .

Done.

**Review by calummoore — APPROVED** [review]

**Comment by timmyjose** [comment]
Working on integrating the changes from `main` locally. Will push update once ready.

**Pull request merged**
